// Single source of truth for the public API reference (served at /api/v1/docs and rendered in the app).
export const API_DOCS = {
  name: 'Aurelune API',
  version: 'v1',
  base: '/api/v1',
  auth: 'Send `Authorization: Bearer aur_…` with a personal API token created under Settings → Developers. Browsers can also pass `?access_token=` (needed for EventSource and <audio> tags). Tokens are limited to the scopes you tick.',
  notes: [
    'The web app, desktop app and mobile apps all use this same API — anything they can do, your integration can do.',
    'All ids are opaque strings. Timestamps are ISO-8601 UTC. Lists paginate with `limit` and a `next_before` cursor.',
    'CORS is open for token-authenticated requests, so browser-based integrations work without a proxy.',
  ],
  endpoints: [
    { group: 'Listening', method: 'GET', path: '/me/player', scope: 'player', desc: 'What you are playing right now (or your last played item when idle).' },
    { group: 'Listening', method: 'GET', path: '/me/player/stream', scope: 'player', desc: 'Server-Sent Events. Emits a `player` event whenever playback changes — for overlays, chat-bot statuses, presence. The server closes each stream after ~9 seconds (serverless hosts cap how long a request can run), so use a client that reconnects — browsers\' EventSource does this automatically. Updates arrive within a couple of seconds.' },
    { group: 'Listening', method: 'GET', path: '/me/history', scope: 'history', desc: 'Your listening history, newest first. Params: limit (≤1000), before, after, kind=track|episode. Follow `next_before` to page through everything.' },
    { group: 'Listening', method: 'GET', path: '/me/history.csv', scope: 'history', desc: 'Your entire history as a CSV download.' },
    { group: 'Listening', method: 'POST', path: '/me/plays', scope: 'history', desc: 'Scrobble a listen from an external player. Body: { kind, id, ms_played, played_at?, source? }. Counts when ≥30s (or half of a short track).' },
    { group: 'Listening', method: 'GET', path: '/me/stats', scope: 'history', desc: 'Totals, streak, per-day minutes for 30 days and an hour-of-day heatmap. Params: range=day|week|month|6months|year|all, tz_offset (minutes).' },
    { group: 'Listening', method: 'GET', path: '/me/top/tracks', scope: 'history', desc: 'Your most played tracks. Params: range, limit.' },
    { group: 'Listening', method: 'GET', path: '/me/top/artists', scope: 'history', desc: 'Your most played artists. Params: range, limit.' },
    { group: 'Listening', method: 'GET', path: '/me/top/genres', scope: 'history', desc: 'Your most played genres. Params: range.' },
    { group: 'Library', method: 'GET', path: '/library', scope: 'library', desc: 'Overview: liked count, playlists, followed artists, saved albums, followed shows.' },
    { group: 'Library', method: 'GET', path: '/me/likes', scope: 'library', desc: 'Liked songs, newest first. Params: limit, offset.' },
    { group: 'Library', method: 'PUT', path: '/me/likes/:trackId', scope: 'library', desc: 'Like a track (goes to Liked Songs). DELETE removes the like.' },
    { group: 'Library', method: 'PUT', path: '/me/likes/episodes/:episodeId', scope: 'library', desc: 'Like a podcast episode (goes to Liked Episodes, not Liked Songs). DELETE removes the like.' },
    { group: 'Library', method: 'GET', path: '/me/likes/episodes', scope: 'library', desc: 'Your liked episodes, newest first.' },
    { group: 'Library', method: 'PUT', path: '/me/following/artists/:id', scope: 'library', desc: 'Follow an artist. DELETE unfollows. Same shape for /me/following/shows/:id and /me/saved/albums/:id.' },
    { group: 'Playlists', method: 'GET', path: '/me/playlists', scope: 'playlists', desc: 'Your playlists.' },
    { group: 'Playlists', method: 'POST', path: '/playlists', scope: 'playlists', desc: 'Create a playlist. Body: { title, description?, is_public?, track_ids? }.' },
    { group: 'Playlists', method: 'GET', path: '/playlists/:id', scope: null, desc: 'A playlist with its tracks. Public playlists need no token.' },
    { group: 'Playlists', method: 'POST', path: '/playlists/:id/tracks', scope: 'playlists', desc: 'Add tracks. Body: { track_ids: [...] }. DELETE /playlists/:id/tracks/:trackId removes one.' },
    { group: 'Account', method: 'GET', path: '/me', scope: 'profile', desc: 'Your profile and creator status.' },
    { group: 'Account', method: 'GET', path: '/me/export', scope: 'export', desc: 'Everything in one JSON file: profile, likes, playlists, follows and your full listening history.' },
    { group: 'Account', method: 'GET', path: '/me/eq', scope: 'profile', desc: 'Your equalizer setting (preset or custom bands), applied client-side during playback.' },
    { group: 'Account', method: 'PUT', path: '/me/eq', scope: 'profile', desc: 'Set your equalizer. Body: { preset } for a named preset, or { bands: [7 numbers, -12..12] } for custom.' },
    { group: 'Library', method: 'PUT', path: '/me/excluded/:trackId', scope: 'library', desc: 'Stop recommending a track in Trending/Discover. DELETE to undo.' },
    { group: 'Account', method: 'POST', path: '/reports', scope: null, desc: 'Report a track, episode, artist, album, show, or playlist. Body: { kind, item_id, reason, note? }.' },
    { group: 'Catalog', method: 'GET', path: '/search', scope: null, desc: 'Search tracks, artists, albums, shows, episodes and public playlists. Param: q.' },
    { group: 'Catalog', method: 'GET', path: '/tracks/:id', scope: null, desc: 'One track. GET /tracks?ids=a,b,c fetches up to 50.' },
    { group: 'Catalog', method: 'GET', path: '/tracks/:id/lyrics', scope: null, desc: 'Lyrics as { synced, lines: [{ t, text }], plain }. `t` is milliseconds when synced.' },
    { group: 'Catalog', method: 'GET', path: '/artists/:idOrSlug', scope: null, desc: 'Artist page: top tracks, releases, shows, followers, monthly listeners.' },
    { group: 'Catalog', method: 'GET', path: '/albums/:id', scope: null, desc: 'A release with its tracklist.' },
    { group: 'Catalog', method: 'GET', path: '/shows/:id', scope: null, desc: 'A podcast with its episodes.' },
    { group: 'Catalog', method: 'GET', path: '/stream/track/:id', scope: null, desc: 'Audio stream with HTTP Range support. Episodes: /stream/episode/:id.' },
    { group: 'Public', method: 'GET', path: '/users/:username', scope: null, desc: 'A listener’s public profile: public playlists and, if they share activity, their top artists this month.' },
    { group: 'Public', method: 'GET', path: '/users/:username/now-playing', scope: null, desc: 'What a listener is playing now — only if they turned on “Share my activity”.' },
  ],
};
